name: Interfaces
# runs tests for specified interface

on:
  workflow_call:
    inputs:
      # See workflow_dispatch descriptions.
      charm:
        required: true
        type: string
      charm_repo:
        required: false
        type: string
        default: ''
      charm_branch:
        required: false
        type: string
        default: ''
  workflow_dispatch:
    inputs:
      charm:
        description: Name of the charm to run interface tests for.
        required: true
        type: string
      charm_repo:
        description: Reference to charm repository suitable for use with `git clone`, e.g. `https://github.com/canonical/vault-k8s-operator.git`. Read from charm config if not provided.
        required: false
        type: string
        default: ''
      charm_branch:
        description: Reference to branch to checkout, suitable for use with `git clone --branch`, e.g. `main`. Read from charm config if not provided.
        required: false
        type: string
        default: ''

jobs:
  init:
    runs-on: ubuntu-latest
    outputs:
      checkout-repository: ${{ steps.init.outputs.repository }}
      checkout-ref: ${{ steps.init.outputs.ref }}
      include: ${{ steps.include.outputs.result }}
    steps:
      - name: Configure repository and ref for checkout
        id: init
        run: |
          set -xueo pipefail
          # $GITHUB_WORKFLOW_REF looks like: octo-org/shared-actions/path/to/workflow.yml@main
          REPOSITORY=$(echo "$GITHUB_WORKFLOW_REF" | awk -F'/' '{print $1"/"$2}')
          REF=$(echo "$GITHUB_WORKFLOW_REF" | awk -F'@' '{print $NF}')
          echo "repository=$REPOSITORY" >> $GITHUB_OUTPUT
          echo "ref=$REF" >> $GITHUB_OUTPUT
      - uses: actions/checkout@v5
        with:
          repository: ${{ steps.init.outputs.repository }}
          ref: ${{ steps.init.outputs.ref }}
      - uses: astral-sh/setup-uv@v6
      - name: Define interface test matrix
        id: include
        env:
          CHARM: ${{ inputs.charm }}
        run: |
          set -xueo pipefail
          ARRAYS=()
          for interface in $(.scripts/ls.py interfaces --name-only | jq --raw-output '.[]'); do
            targets=$(.scripts/get-interface-test-targets.py "$interface" --only-charm "$CHARM" --include-interface --exclude-charm)
            ARRAYS+=("$targets")
          done
          INCLUDE=$(printf "%s\n" "${ARRAYS[@]}" | jq -s 'add')
          echo "$INCLUDE" | jq  # logging
          echo "result=$INCLUDE" >> "$GITHUB_OUTPUT"

  tests:
    needs: [init]
    if: ${{ needs.init.outputs.include != '[]' }}
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJSON(needs.init.outputs.include) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          repository: ${{ needs.init.outputs.checkout-repository }}
          ref: ${{ needs.init.outputs.checkout-ref }}
      - uses: astral-sh/setup-uv@v6
      - name: Run interface tests
        run: |
          set -xueo pipefail
          .scripts/run-interface-tests.py \
            ${{ matrix.interface }} \
            ${{ matrix.version }} \
            ${{ matrix.role }} \
            ${{ inputs.charm_name }} \
            ${{ matrix.endpoint }} \
            --charm-repo '${{ inputs.charm_repo }}' \
            --charm-branch '${{ inputs.charm_branch }}'

