name: CI

on:
  push:
    branches:
      - v0
  pull_request:
  workflow_dispatch:

jobs:
  interfaces:
    strategy:
      fail-fast: false
      matrix:
        charm: [tempo-coordinator-k8s]
    uses: ./.github/workflows/charm-interface-tests.yaml
    with:
      charm: ${{ matrix.charm }}
