name: CI

on:
  push:
    branches:
      - interface-tests-v0
  pull_request:
  workflow_dispatch:

jobs:
  charms:
    strategy:
      fail-fast: false
      matrix:
        charm:
          - pyroscope-coordinator-k8s
          - tempo-coordinator-k8s
    uses: ./.github/workflows/interface-tests.yaml
    with:
      charm: ${{ matrix.charm }}

  charm-with-charm-repo:
    uses: ./.github/workflows/interface-tests.yaml
    with:
      charm: tempo-coordinator-k8s
      charm-repo: canonical/tempo-operators

  charm-with-charm-repo-and-charm-branch:
    uses: ./.github/workflows/interface-tests.yaml
    with:
      charm: tempo-coordinator-k8s
      charm-repo: canonical/tempo-operators
      charm-branch: main

  charm-with-charm-branch-only:
    uses: ./.github/workflows/interface-tests.yaml
    with:
      charm: tempo-coordinator-k8s
      charm-branch: main

  zizmor:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      - uses: astral-sh/setup-uv@v6
      - run: uvx zizmor@v1.11.0 --format=sarif . > results.sarif
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
          category: zizmor
