name: CI
# runs linting for whole repository, and:
# on PR: runs tests for packages and interfaces with changes (or all if global files are changed)
# on push to main or on dipatch: runs tests for all packages and interfaces

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  fast-lint:
    uses: ./.github/workflows/fast-lint.yaml

  init:
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.packages.outputs.result }}
      interfaces: ${{ steps.interfaces.outputs.result }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: astral-sh/setup-uv@v6
      - name: Collect changed packages
        id: packages
        run: .github/get-changed.py packages ${{ github.event.pull_request.base.sha }}
      - name: Collect changed interfaces
        id: interfaces
        run: .github/get-changed.py interfaces ${{ github.event.pull_request.base.sha }}

  tests:
    needs: [fast-lint, init]
    if: ${{ needs.init.outputs.packages != '[]' }}
    strategy:
      fail-fast: false
      matrix:
        package: ${{ fromJson(needs.init.outputs.packages) }}
    uses: ./.github/workflows/tests.yaml
    with:
      package: ${{ matrix.package }}

  tests-passed:
    needs: [tests]
    if: ${{ !cancelled() }}  # run even if tests are skipped or failed
    runs-on: ubuntu-latest
    steps:
      - name: Fail if any tests failed
        if: ${{ needs.tests.result != 'success' && needs.tests.result != 'skipped' }}
        run: |
          echo '${{ toJSON(needs) }}'
          exit 1

  interface-tests:
    needs: [fast-lint, init]
    if: ${{ needs.init.outputs.interfaces != '[]' }}
    strategy:
      fail-fast: false
      matrix:
        interface: ${{ fromJson(needs.init.outputs.interfaces) }}
    uses: ./.github/workflows/interface-tests.yaml
    with:
      interface: ${{ matrix.interface }}

  interface-tests-passed:
    needs: [interface-tests]
    if: ${{ !cancelled() }}  # run even if tests are skipped or failed
    runs-on: ubuntu-latest
    steps:
      - name: Fail if any interface tests failed
        if: ${{ needs.interface-tests.result != 'success' && needs.interface-tests.result != 'skipped' }}
        run: |
          echo '${{ toJSON(needs) }}'
          exit 1

  template-and-example-in-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
      - run: |
          uvx --from rust-just just init --no-input
          rm -rf .example
          mv example .example
          # check if tracked files changed, or any new files were added
          # (git diff --exit-code isn't effected by new files)
          STATUS=$(git status --porcelain)
          echo "$STATUS"
          test -z "$STATUS"

  template-and-interface-example-in-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
      - working-directory: interfaces
        run: |
          uvx --from rust-just just interface init --no-input
          rm -rf .example
          mv example .example
          # check if tracked files changed, or any new files were added
          # (git diff --exit-code isn't effected by new files)
          STATUS=$(git status --porcelain)
          echo "$STATUS"
          test -z "$STATUS"
