name: CI

on:
  push:
    branches:
      - interface-tests-v0
  pull_request:
  workflow_dispatch:

jobs:
  charms:
    strategy:
      fail-fast: false
      matrix:
        charm:
          - pyroscope-coordinator-k8s
          - tempo-coordinator-k8s
    uses: ./.github/workflows/interface-tests.yaml
    with:
      charm: ${{ matrix.charm }}
