#
name: Docs

on:
  push:
    branches:
      - main
  pull_request:
  workflow_call:
  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docchecks:
    name: Checks
    runs-on: ubuntu-22.04
    outputs:
      spellcheck-result: ${{ steps.spellcheck-step.outcome }}
      linkcheck-result: ${{ steps.linkcheck-step.outcome }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Spelling
        id: spellcheck-step
        if: success() || failure()
        continue-on-error: true
        uses: canonical/documentation-workflows/spellcheck@6f9c05eae99ca9fff05250810bba2a71a380ebd1  # main
        with:
          working-directory: .docs
      - name: Links
        id: linkcheck-step
        if: success() || failure()
        run: |
          set -xueo pipefail
          uvx --from rust-just just docs linkcheck ${{ github.event_name != 'pull_request' && '--tag check-github-links' || '' }}
      - name: Markdown lint
        id: markdown-step
        if: success() || failure()
        uses: DavidAnson/markdownlint-cli2-action@992badcdf24e3b8eb7e87ff9287fe931bcb00c6e  # v20.0.0
        with:
          config: ".docs/.sphinx/.markdownlint.json"
      - name: Local Sphinx extensions static analysis
        if: success() || failure()
        run: uvx --from=rust-just just docs ext-static
      - name: Local Sphinx extensions unit tests
        if: success() || failure()
        run: uvx --from=rust-just just docs ext-unit
