name: Interface tests
# runs tests for specified interface

on:
  workflow_call:
    inputs:
      interface:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      interface:
        description: Interface (by path) to run tests for.
        required: true
        type: string

jobs:
  init:
    runs-on: ubuntu-latest
    outputs:
      include: ${{ steps.include.outputs.result }}
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
      - name: Define interface test matrix
        id: include
        run: |
          INCLUDE=$(.scripts/get-interface-test-targets.py ${{ inputs.interface }})
          echo "result=$INCLUDE" >> "$GITHUB_OUTPUT"

  tests:
    needs: [init]
    if: ${{ needs.init.outputs.include != '[]' }}
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJSON(needs.init.outputs.include) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
      - name: Run interface tests
        run: .scripts/run-interface-tests.py \
            ${{ inputs.interface }} \
            ${{ matrix.version }} \
            ${{ matrix.role }} \
            ${{ matrix.charm_name }} \
            ${{ matrix.endpoint }}

  interface-tests-passed-or-skipped:
    needs: [tests]
    if: ${{ !cancelled() }}  # run even if tests are skipped or failed
    runs-on: ubuntu-latest
    steps:
      - name: Fail if any test matrix jobs failed
        if: ${{ needs.tests.result != 'success' && needs.tests.result != 'skipped' }}
        run: |
          echo '${{ toJSON(needs) }}'
          exit 1
