name: Publish

on:
  push:
    tags:
      - 'charmlibs-v[0-9]*'
      - 'pathops-v[0-9]*'
  workflow_dispatch:
    inputs:
      package:
        description: Package to be published to test.pypi.org
        required: true
        type: string
      skip-juju:
        description: Skip Juju integration tests
        required: false
        type: boolean

jobs:
  unify-inputs:
    runs-on: ubuntu-latest
    outputs:
      package: ${{ steps.main.outputs.package }}
      skip-juju:  ${{ steps.main.outputs.skip-juju }}
      repository-url:  ${{ steps.main.outputs.repository-url }}
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - id: main
        run: uv run --no-project --script .github/unify-publish-inputs.py

  debug:
    runs-on: ubuntu-latest
    needs: unify-inputs
    steps:
      - name: Debug
        env:
          PACKAGE: ${{ needs.unify-inputs.outputs.package }}
          SKIP: ${{ needs.unify-inputs.outputs.skip-juju }}
          SKIP_EQUALS_TRUE: ${{ needs.unify-inputs.outputs.skip-juju == true }}
          SKIP_NEQUALS_FALSE: ${{ needs.unify-inputs.outputs.skip-juju != false }}
          REPO:  ${{ needs.unify-inputs.outputs.repository-url }}
        run: echo

  tests:
    needs: unify-inputs
    uses: ./.github/workflows/tests.yaml
    with:
      package: ${{ needs.unify-inputs.outputs.package }}
      skip-juju: ${{ needs.unify-inputs.outputs.skip-juju == true }}

  build-n-publish:
    needs: [unify-inputs,tests]
    name: Build and publish ${{ needs.unify-inputs.outputs.package }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      attestations: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Build
        run: uv build
        working-directory: ./${{ needs.unify-inputs.outputs.package }}
      - name: Attest build provenance
        uses: actions/attest-build-provenance@v2.4.0
        with:
          subject-path: '${{ needs.unify-inputs.outputs.package }}/dist/*'
      - name: Publish
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: ./${{ needs.unify-inputs.outputs.package }}/dist/
          repository-url: ${{ needs.unify-inputs.outputs.repository-url }}
          verbose: true
