name: Publish a package

on:
  workflow_call:
    inputs:
      package:
        required: true
        type: string
      skip-juju:
        required: false
        type: boolean
      repository-url:
        # One of:
        # https://upload.pypi.org/legacy/
        # https://test.pypi.org/legacy/
        default: https://upload.pypi.org/legacy/
        required: false
        type: string

jobs:
  tests:
    uses: ./.github/workflows/tests.yaml
    with:
      package: ${{ inputs.package }}
      skip-juju: ${{ inputs.skip-juju }}
  build-n-publish:
    needs: tests
    name: Build and publish package
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      attestations: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Build
        run: uv build
        working-directory: ./${{ inputs.package }}
      - name: Attest build provenance
        uses: actions/attest-build-provenance@v2.4.0
        with:
          subject-path: '${{ inputs.package }}/dist/*'
      - name: Publish
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: ./${{ inputs.package }}/dist/
          repository-url: ${{ inputs.repository-url }}
