name: Tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_call:

jobs:
  packages:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.packages.outputs.changed }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - id: packages
        run: |
          PACKAGES=$(git diff --name-only origin/${{ github.base_ref || 'main' }} -- | grep ^packages | cut -d'/' -f2 | uniq)
          if [[ $PACKAGES ]]; then
            JSON=$(echo $PACKAGES | jq --raw-input --slurp --compact-output 'split("\n")[:-1]')
            echo $JSON >> "$GITHUB_OUTPUT"
          else
            echo '[]' >> "$GITHUB_OUTPUT"
          fi

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Run linting
        run: uvx --from rust-just just lint

  test:
    needs: packages
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package: ${{ fromJson(needs.packages.outputs.changed) }}
        recipe: [ 'static', 'unit']
        python-version: [
          '3.8',  # oldest supported by Ops
          '3.12',  # latest Ubuntu LTS
          '3.13',  # latest Python release
        ]
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Run ${{ matrix.just-recipe }} tests
        run: uvx --from rust-just just package=${{ matrix.package }} python=${{ matrix.python-version }} ${{ matrix.recipe }}

  pebble:
    needs: packages
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package: ${{ fromJson(needs.packages.outputs.changed) }}
        pebble-version: [
          'v1.1.1',  # Juju 2.9.50 LTS
          # 'v1.7.4',  # Juju 3.4.6
          # 'v1.10.2',  # Juju 3.5.7
          'v1.19.0',  # Juju 3.6.4 LTS
          'master',
        ]
        python-version: [
          '3.8',  # oldest supported by Ops
          '3.12',  # latest Ubuntu LTS
          '3.13',  # latest Python release
        ]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          # To suppress the "Restore cache failed" error, since there is no go.sum file here.
          cache: false

      - name: Install Pebble
        run: go install github.com/canonical/pebble/cmd/pebble@${{ matrix.pebble-version }}

      - name: Start Pebble
        run: |
          umask 0
          $HOME/go/bin/pebble run --create-dirs &
        env:
          PEBBLE: /tmp/pebble-test

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Run Pebble integration tests
        run: uvx --from rust-just just package=${{ matrix.package }} python=${{ matrix.python-version }} pebble
        env:
          PEBBLE: /tmp/pebble-test
