name: Test publish 'charmlibs' package
on:
  workflow_dispatch:

jobs:
  publish:
    uses: ./.github/workflows/publish.yaml
    with: 
      package: _charmlibs
      repository-url: https://test.pypi.org/legacy/
