name: Test publish 'charmlibs-pathops' package
on:
  workflow_dispatch:

jobs:
  publish:
    uses: ./.github/workflows/publish.yaml
    with: 
      package: pathops
      repository-url: https://test.pypi.org/legacy/
